import pandas as pd
from pathlib import Path


RAW_DATA_DIR = Path(__file__).resolve().parent.parent / "data" / "raw"
PROCESSED_DATA_DIR = Path(__file__).resolve().parent.parent / "data" / "processed"

PROCESSED_DATA_DIR.mkdir(parents=True, exist_ok=True)

def inspect_raw_data():

    folders = [
        "race_results",
        "qualifying",
        "laps",
        "stints",
        "pit_stops",
        "weather"
    ]

    all_files = {}

    for folder in folders:

        folder_path = RAW_DATA_DIR / folder

        files = list(folder_path.glob("*.csv"))

        # Keep only files generated by our automated pipeline
        files = [
            file for file in files
            if file.name.count("_") >= 2
            and file.name.endswith("_grand_prix.csv")
        ]

        all_files[folder] = files

        print(f"{folder}: {len(files)} files")

    print("\n" + "=" * 60)
    print("DATASET CONSISTENCY CHECK")
    print("=" * 60)

    reference_files = {
        file.name
        for file in all_files["race_results"]
    }

    for folder in folders:

        current_files = {
            file.name
            for file in all_files[folder]
        }

        missing = reference_files - current_files
        extra = current_files - reference_files

        print(f"\n{folder.upper()}")

        if not missing and not extra:
            print("✓ Matches race results")

        if missing:
            print("Missing:")
            for file in sorted(missing):
                print(f"  - {file}")

        if extra:
            print("Extra:")
            for file in sorted(extra):
                print(f"  - {file}")

def combine_race_results():
    race_folder = RAW_DATA_DIR / "race_results"

    files = [
        file for file in race_folder.glob("*.csv")
        if file.name.endswith("_grand_prix.csv")
    ]

    all_races = []

    for file in files:
        df = pd.read_csv(file)

        # Ignore empty files
        if df.empty:
            print(f"Skipping empty file: {file.name}")
            continue

        year = int(file.name[:4])
        race_name = file.stem[5:].replace("_", " ")

        df["Year"] = year
        df["Race"] = race_name

        all_races.append(df)

    master_df = pd.concat(
        all_races,
        ignore_index=True
    )

    output_file = PROCESSED_DATA_DIR / "master_race_results.csv"

    master_df.to_csv(
        output_file,
        index=False
    )

    print("\nMaster race-results dataset created!")
    print(f"Rows: {len(master_df)}")
    print(f"Columns: {len(master_df.columns)}")
    print(f"Saved to: {output_file}")

def combine_qualifying_results():

    qualifying_folder = RAW_DATA_DIR / "qualifying"

    files = [
        file for file in qualifying_folder.glob("*.csv")
        if file.name.endswith("_grand_prix.csv")
    ]

    all_qualifying = []

    for file in files:

        df = pd.read_csv(file)

        year = int(file.name[:4])

        race_name = file.stem[5:].replace("_", " ")

        df["Year"] = year
        df["Race"] = race_name

        all_qualifying.append(df)

    qualifying_df = pd.concat(
        all_qualifying,
        ignore_index=True
    )

    output_file = (
        PROCESSED_DATA_DIR / "master_qualifying_results.csv"
    )

    qualifying_df.to_csv(
        output_file,
        index=False
    )

    print("\nMaster qualifying dataset created!")
    print(f"Rows: {len(qualifying_df)}")
    print(f"Columns: {len(qualifying_df.columns)}")
    print(f"Saved to: {output_file}")

def clean_race_results(df):

    cleaned_df = df.copy()

    cleaned_df = cleaned_df.drop(
        columns=[
            "BroadcastName",
            "TeamColor",
            "HeadshotUrl",
            "CountryCode",
            "Q1",
            "Q2",
            "Q3"
        ]
    )

    return cleaned_df

if __name__ == "__main__":

    combine_race_results()
    combine_qualifying_results()

    master_df = pd.read_csv(
        PROCESSED_DATA_DIR / "master_race_results.csv"
    )

    cleaned_df = clean_race_results(master_df)

    cleaned_file = (
        PROCESSED_DATA_DIR / "cleaned_race_results.csv"
    )

    cleaned_df.to_csv(
        cleaned_file,
        index=False
    )

    print("\nCleaned dataset created.")
    print(f"Shape: {cleaned_df.shape}")
    print(f"Saved to: {cleaned_file}")

qualifying_df = pd.read_csv(
    PROCESSED_DATA_DIR / "master_qualifying_results.csv"
)

print("\n" + "=" * 60)
print("QUALIFYING RECORDS BY YEAR")
print("=" * 60)

print(
    qualifying_df.groupby("Year").size()
)

print("\n" + "=" * 60)
print("QUALIFYING RECORDS BY YEAR AND RACE")
print("=" * 60)

print(
    qualifying_df.groupby(
        ["Year", "Race"]
    ).size()
)

race_df = pd.read_csv(
    PROCESSED_DATA_DIR / "master_race_results.csv"
)

print("\n" + "=" * 60)
print("RACE RECORDS BY YEAR")
print("=" * 60)

print(
    race_df.groupby("Year").size()
)

print("\n" + "=" * 60)
print("NUMBER OF RACES BY YEAR")
print("=" * 60)

print(
    race_df.groupby("Year")["Race"].nunique()
)

print("\n" + "=" * 60)
print("RACES COLLECTED BY YEAR")
print("=" * 60)

for year in sorted(race_df["Year"].unique()):

    print(f"\n{year}")

    races = sorted(
        race_df.loc[
            race_df["Year"] == year,
            "Race"
        ].unique()
    )

    for race in races:
        print(f"  - {race}")